name: upload APK

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'    

      - name: Build Apk
        run: |
          cd  my_app
          flutter build apk --release    
      
      - name: Get dependencies
        run: |
          cd my_app
          flutter pub get

      - name: Upload to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: my_app/build/app/outputs/flutter-apk/app-release.apk